// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnthkbwjqbsrzmawynjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJudGhrYndqcWJzcnptYXd5bmpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzYyNTQsImV4cCI6MjA2ODkxMjI1NH0.ZealYZeMkTZXmVF8b-qrQ3iHejtCNlfcmFhB8gG0c2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});